modLoader = "javafml" #mandatory
loaderVersion = "[37,)" #mandatory
license = "MIT"
issueTrackerURL="https://github.com/65-7a/nullifier/issues/" #optional
[[mods]] #mandatory
modId = "nullifier" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Nullifier" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/nullifier/" #optional
logoFile="icon.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "65_7a" #optional
description = '''
A simple mod adding one block: the nullifier.

'''
